#!/usr/bin/env bash

image=${IMAGE-quay.io/konveyor/analyzer-lsp}

if [ -z "${image}" ]
then
  exit
fi

addon=/tmp/addon

params=()
for p in "$@"
do
  params+=("$p")
done
docker run \
  --entrypoint /usr/local/bin/konveyor-analyzer-dep \
  -v ${addon}:${addon} \
  ${image} \
  "${params[@]}"

