#!/usr/bin/env bash

image=${IMAGE-quay.io/konveyor/windup-shim}

if [ -z "${image}" ]
then
  exit
fi

addon=/tmp/addon

params=()
for p in "$@"
do
  params+=("$p")
done

docker run \
  -v ${addon}:${addon} \
  ${image} \
  "${params[@]}"

